spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myweb
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

mybatis:
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 8081
